### PR TITLE
Adding KubeCon to the list

### PR DESCRIPTION
**Pull request by Marwan01**
Added KubeCon and myself as contributor to the readme following the guidelines and code of conduct.

### CODE REVIEW

**Comment by Marwan01** [comment]
The added commit takes care of this issue: https://github.com/fvcproductions/diversify-me/issues/13

**Review by jessicaxiejw — APPROVED** [review]

**Comment by jessicaxiejw** [comment]
Thank you for adding the event for me :)

**Comment by FrancesCoronel** [comment]
LGTM

**Comment by EYITAY** [comment]
Add  [DjangoConEU](https://2020.djangocon.eu/) and here is the scholarship application [form ](https://docs.google.com/forms/d/e/1FAIpQLSeG5d9SKIEs7fUj3kzmdxY2ardOO7Aqfp3YOQrLqRxzlKdZ0g/viewform)

**Comment by FrancesCoronel** [comment]
@EYITAY please open a new issue, thank you

**Pull request merged**
